-- PROCEDURE, COM PARÂMETROS DE QT ALUNOS E QT QUESTÕES/COLUNAS

CREATE PROCEDURE sp_Colunas @QTALUNO INT, @QTCOL INT
AS
    DECLARE @Q VARCHAR(1), @NUM INT, @QUESTAO VARCHAR(3), @ALUCONT INT, @COLCONT INT

    SET @Q = 'Q'
    SET @NUM = 1
    SET @ALUCONT = 1
    SET @COLCONT = 1

    WHILE @ALUCONT <= @QTALUNO
    BEGIN
        EXEC('INSERT INTO QUESTIONARIO VALUES (' + @ALUCONT + ')')
        SET @ALUCONT += 1
    END

    WHILE @COLCONT <= @QTCOL
    BEGIN
        SET @ALUCONT = 1
        SET @QUESTAO = CONCAT(@Q,@COLCONT)
        EXEC('ALTER TABLE QUESTIONARIO ADD ' + @QUESTAO + ' INT')
    
        WHILE @ALUCONT <= @QTALUNO
        BEGIN        
            EXEC('UPDATE QUESTIONARIO SET ' + @QUESTAO + ' = ' + @NUM + ' WHERE cd_Aluno = ' + @ALUCONT)
            SET @ALUCONT += 1
            SET @NUM += 1 -- PARA TESTE
        END
    
        SET @COLCONT += 1
    
        SELECT * FROM QUESTIONARIO
    END
